name: Notify Bing IndexNow

on:
  push:
    branches: [ work ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify IndexNow
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.sha }}
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
          BASE_URL: https://www.digitalcare.site
        run: node .github/scripts/indexnow.js
